#!/bin/bash
#docker stop $(sudo docker ps -qa);
#docker system prune -f
docker load < agroecoRender.tar.gz
docker load < agroecoSim.tar.gz
docker load < agroecoWeb.tar.gz
docker load < tamashii.tar.gz