services:
  simulation:
    image: agroecosim
    ports:
      - "7215:80"
  renderer:
    image: agroecorender
    ports:
      - "9000:9000"
  web:
    image: agroecoweb
    ports:
      - "8080:8080"