#https://varhowto.com/install-miniconda-ubuntu-20-04/
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS publish
COPY . .
#fix https://github.com/dotnet/dotnet-docker/issues/2470
ENV COMPlus_EnableDiagnostics=0
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
ENV ASPNETCORE_ENVIRONMENT='Production'

WORKDIR AgroServer

ARG BACKEND
RUN dotnet restore --runtime alpine-x64
#--disable-parallel

RUN dotnet publish \
    --configuration Release \
    -p:Platform=x64 \
    --framework=net6.0 \
    --nologo \
    --runtime alpine-x64 \
    --no-self-contained \
    -p:PublishReadyToRun=true \
    -p:PublishReadyToRunShowWarnings=true \
    #-p:PublishTrimmed=true \
    --output /app/
#--verbosity detailed

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS final
WORKDIR /app
ENV COMPlus_EnableDiagnostics=0
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
ENV ASPNETCORE_ENVIRONMENT='Production'
ENV AGRO_HOSTNAME=${BACKEND}
#only copy the published app folder into the final image, everything else (the whole src) is ignored
COPY --from=publish /app .

RUN apk update && apk add --no-cache ca-certificates && apk --no-cache add tzdata && apk upgrade -U --no-cache && rm -rf /var/cache/apk/*
#COPY --from=publish harden.sh .
#RUN chmod +x harden.sh && sh harden.sh && rm harden.sh
#USER user:user

RUN addgroup -g 61000 docker && adduser -g 61000 -H -D -s /bin/false -u 61000 docker -G docker
USER docker

#does nothing, just documents the exposed port
EXPOSE 7215
ENTRYPOINT ["./AgroServer"]