FROM node:18-alpine AS build

ARG BACKEND

WORKDIR app
COPY ThreeFrontend/ .

RUN echo "export const BackendURI = \"${BACKEND}\";" > src/config.ts

RUN npm install -g npm@latest && npm install && npm install @microsoft/signalr
RUN npx cross-env NODE_OPTIONS=--openssl-legacy-provider preact build --no-prerender

FROM node:18-alpine AS final
EXPOSE 8080
WORKDIR /app

COPY --from=build /app/build .
RUN npm install -g npm@latest && npm install sirv-cli

ENTRYPOINT ["npx", "sirv", ".", " --cors", "--single", "--host"]
