services:
  simulation:
    image: agroecosim
    ports:
      - "7215:80"
    restart: on-failure
  mitsuba:
   image: agroecorender
   expose:
     - "9001"
   restart: on-failure
  web:
    image: agroecoweb
    ports:
      - "8080:8080"
    restart: on-failure
  tamashii:
    image: tamashii
    expose:
      - "9000"
    restart: on-failure
    #entrypoint: "vulkaninfo --summary"
    #entrypoint: "nvidia-smi"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu,graphics,compute,utility]
    runtime: "nvidia"
    volumes:
      - '/etc/vulkan/icd.d/nvidia_icd.json:/etc/vulkan/icd.d/nvidia_icd.json'
      - '/etc/vulkan/implicit_layer.d/nvidia_layers.json:/etc/vulkan/implicit_layer.d/nvidia_layers.json'
      - '/usr/share/glvnd/egl_vendor.d/10_nvidia.json:/usr/share/glvnd/egl_vendor.d/10_nvidia.json'
    devices:
      - /dev/dri:/dev/dri